name: UltraGadgets
version: 1.0
main: com.floodeer.gadgets.Main
description: Gadgets Test!
softdepend: [ProtocolLib, OverlandsAPI]
commands:
  ultragadgets:
   description: Usar os Gadgets!
   aliases: [ug]